In [2]:
lst = ['a', 'b', 'b', 'c', 'c', 'c']
freq_dict = {}

for i in lst:
    if i not in freq_dict.keys():
        freq_dict[i] = 1
    else:
        freq_dict[i] += 1
        
freq_dict

{'a': 1, 'b': 2, 'c': 3}

In [3]:
lst = [3, 1, 2, 3]
sorted(lst)

[1, 2, 3, 3]

In [4]:
lst

[3, 1, 2, 3]

In [5]:
lst.sort()

In [6]:
lst

[1, 2, 3, 3]

In [7]:
import numpy as np

In [8]:
a = np.array([[1, 4, -3],
              [0, 7, 2],
              [9, 3, 4]])

# each line
np.argmin(a, axis=1)

array([2, 0, 1], dtype=int64)

In [9]:
# each col
np.argmin(a, axis=0)

array([1, 2, 0], dtype=int64)

In [10]:
lst = [3, 1, 2, 3]
list(reversed(lst))

[3, 2, 1, 3]

In [11]:
lst

[3, 1, 2, 3]

In [12]:
lst[::-1]

[3, 2, 1, 3]

In [13]:
lst

[3, 1, 2, 3]

In [14]:
def append(elt, seq=None):
    if seq == None:
        seq = []
    seq.append(elt)
    return seq

# seq is assigned to []
append(1)

[1]

In [16]:
# seq is assigned to [] again
append(2)

[2]

In [17]:
lst = [1]
append(2, lst)
lst

[1, 2]

- Toy data sets are clean and tidy
- Real data sets are messy and dirty
    - Duplicates


In [18]:
m = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]])

np.diff(m, axis=1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
np.diff(m, axis=0)

array([[5, 5, 5, 5, 5]])

In [20]:
m = np.array([1, 2, 3, 4])
m.itemsize

4

In [21]:
m = np.array([1.1, 2.2])
m.itemsize

8